/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class KmsEncryptDecryptExampleTest {
    @Test
    void kmsExampleExists() {
        assertNotNull(KmsEncryptDecryptExample.class, "KmsEncryptDecryptExample class should exist");
    }
}
